//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Feb22_Session2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public long EmpID { get; set; }
        public string EmpName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> Age { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public Nullable<double> BasicSalary { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblEmployeeType tblEmployeeType { get; set; }
    }
}
